### ISSUE TITLE
test_ClassicLasso_sparco: for LASSO problems with sparco data 

### ISSUE THREAD

**Issue by worry1114** [MatOpt/SuiteLasso#1]
when I input the command:  generateProblem(7)
I got ：A: @(x,mode)opMatrix_intrnl(A,opinfo,x,mode) 
I want to know weather I can get the matrix A of this problem？ 
 and does this A represent the result of A*x, B  represent the result of A^T*x ?

**Comment by MatOpt** [comment]
The generateProblem function comes from the sparco collection.  Please visit the authors' website https://friedlander.io/software/sparco/  for details.
